---
title: "Exploracion"
author: "Juan Gaston"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(kableExtra)
```

## Introducción

### De donde vienes los datos

Estos datos fueron recopilados de la **IUC**, y se obtuvieron del [siguiente repositorio](https://github.com/rfordatascience/tidytuesday) de github 

```{r, echo = FALSE}
plants <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv")
actions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv")
threats <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv")

```

## Datos de Sudamerica

El numero de especies en Sudamerica es `r plants %>% filter(continent == "South America") %>%  nrow ()`



## Tiempo de dormir

```{r, echo = FALSE}
data ("msleep")
table <- msleep %>% 
  group_by(vore) %>% 
  summarise_at("sleep_total", .funs = list(Media = mean, Desvio = sd)) %>% 
  filter(!is.na(vore)) %>% 
  arrange(desc(Media))

kable(table, digit = 2)  %>% 
  kable_styling(bootstrap_options = c("striped","hover","condensed"))
```



## Tablas largas

```{r}
table1 <- diamonds %>% 
  group_by(color) %>% 
  summarise(Precio_Medio = mean(price))

kable(table1) %>% 
  kable_styling(bootstrap_options = c("striped","hover","condensed")) %>% 
  scroll_box(width = "400px", height = "200px")
  
```

